version: "3"

networks:
  backend:
    driver: "bridge"
  
volumes:
  postgres:
    driver: "local"

services:

### PostgreSQL PostGis Container ############################
  postgres:
    build: ./docker/postgres
    volumes:
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - backend

### nodejs Container #######################################
  nodejs:
    build: 
      context: ./docker/nodejs
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - postgres
    volumes:
      - ./:/var/www
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - backend

### pgAdmin Container #######################################
  pgadmin:
    build: ./docker/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    volumes:
      - ${DATA_SAVE_PATH}/pgadmin:/var/lib/pgadmin
    networks:
      - backend

### redis Container #######################################
  redis:
    container_name: redis_bill
    image: redis:latest
    networks:
      - backend